# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import blog_pb2 as blog__pb2


class BlogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createPost = channel.unary_unary(
                '/BlogService/createPost',
                request_serializer=blog__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=blog__pb2.CreatePostResponse.FromString,
                )
        self.getPostCount = channel.unary_unary(
                '/BlogService/getPostCount',
                request_serializer=blog__pb2.GetPostCountRequest.SerializeToString,
                response_deserializer=blog__pb2.GetPostCountResponse.FromString,
                )
        self.getPosts = channel.unary_unary(
                '/BlogService/getPosts',
                request_serializer=blog__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=blog__pb2.GetPostsResponse.FromString,
                )


class BlogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPostCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BlogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createPost': grpc.unary_unary_rpc_method_handler(
                    servicer.createPost,
                    request_deserializer=blog__pb2.CreatePostRequest.FromString,
                    response_serializer=blog__pb2.CreatePostResponse.SerializeToString,
            ),
            'getPostCount': grpc.unary_unary_rpc_method_handler(
                    servicer.getPostCount,
                    request_deserializer=blog__pb2.GetPostCountRequest.FromString,
                    response_serializer=blog__pb2.GetPostCountResponse.SerializeToString,
            ),
            'getPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.getPosts,
                    request_deserializer=blog__pb2.GetPostsRequest.FromString,
                    response_serializer=blog__pb2.GetPostsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BlogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BlogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogService/createPost',
            blog__pb2.CreatePostRequest.SerializeToString,
            blog__pb2.CreatePostResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPostCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogService/getPostCount',
            blog__pb2.GetPostCountRequest.SerializeToString,
            blog__pb2.GetPostCountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BlogService/getPosts',
            blog__pb2.GetPostsRequest.SerializeToString,
            blog__pb2.GetPostsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
