# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nblog.proto\"F\n\x04Post\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x11\n\tcreatedAt\x18\x04 \x01(\x04\"\"\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0b\n\x03msg\x18\x02 \x01(\t\"@\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0b\n\x03uri\x18\x03 \x01(\t\"+\n\x12\x43reatePostResponse\x12\x15\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.Error\"/\n\x0fGetPostsRequest\x12\r\n\x05index\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\"?\n\x10GetPostsResponse\x12\x14\n\x05posts\x18\x01 \x03(\x0b\x32\x05.Post\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"\x15\n\x13GetPostCountRequest\"<\n\x14GetPostCountResponse\x12\x15\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.Error\x12\r\n\x05\x63ount\x18\x02 \x01(\r2\xb2\x01\n\x0b\x42logService\x12\x35\n\ncreatePost\x12\x12.CreatePostRequest\x1a\x13.CreatePostResponse\x12;\n\x0cgetPostCount\x12\x14.GetPostCountRequest\x1a\x15.GetPostCountResponse\x12/\n\x08getPosts\x12\x10.GetPostsRequest\x1a\x11.GetPostsResponseb\x06proto3')



_POST = DESCRIPTOR.message_types_by_name['Post']
_ERROR = DESCRIPTOR.message_types_by_name['Error']
_CREATEPOSTREQUEST = DESCRIPTOR.message_types_by_name['CreatePostRequest']
_CREATEPOSTRESPONSE = DESCRIPTOR.message_types_by_name['CreatePostResponse']
_GETPOSTSREQUEST = DESCRIPTOR.message_types_by_name['GetPostsRequest']
_GETPOSTSRESPONSE = DESCRIPTOR.message_types_by_name['GetPostsResponse']
_GETPOSTCOUNTREQUEST = DESCRIPTOR.message_types_by_name['GetPostCountRequest']
_GETPOSTCOUNTRESPONSE = DESCRIPTOR.message_types_by_name['GetPostCountResponse']
Post = _reflection.GeneratedProtocolMessageType('Post', (_message.Message,), {
  'DESCRIPTOR' : _POST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:Post)
  })
_sym_db.RegisterMessage(Post)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:Error)
  })
_sym_db.RegisterMessage(Error)

CreatePostRequest = _reflection.GeneratedProtocolMessageType('CreatePostRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOSTREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:CreatePostRequest)
  })
_sym_db.RegisterMessage(CreatePostRequest)

CreatePostResponse = _reflection.GeneratedProtocolMessageType('CreatePostResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEPOSTRESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:CreatePostResponse)
  })
_sym_db.RegisterMessage(CreatePostResponse)

GetPostsRequest = _reflection.GeneratedProtocolMessageType('GetPostsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTSREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:GetPostsRequest)
  })
_sym_db.RegisterMessage(GetPostsRequest)

GetPostsResponse = _reflection.GeneratedProtocolMessageType('GetPostsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTSRESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:GetPostsResponse)
  })
_sym_db.RegisterMessage(GetPostsResponse)

GetPostCountRequest = _reflection.GeneratedProtocolMessageType('GetPostCountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTCOUNTREQUEST,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:GetPostCountRequest)
  })
_sym_db.RegisterMessage(GetPostCountRequest)

GetPostCountResponse = _reflection.GeneratedProtocolMessageType('GetPostCountResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPOSTCOUNTRESPONSE,
  '__module__' : 'blog_pb2'
  # @@protoc_insertion_point(class_scope:GetPostCountResponse)
  })
_sym_db.RegisterMessage(GetPostCountResponse)

_BLOGSERVICE = DESCRIPTOR.services_by_name['BlogService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POST._serialized_start=14
  _POST._serialized_end=84
  _ERROR._serialized_start=86
  _ERROR._serialized_end=120
  _CREATEPOSTREQUEST._serialized_start=122
  _CREATEPOSTREQUEST._serialized_end=186
  _CREATEPOSTRESPONSE._serialized_start=188
  _CREATEPOSTRESPONSE._serialized_end=231
  _GETPOSTSREQUEST._serialized_start=233
  _GETPOSTSREQUEST._serialized_end=280
  _GETPOSTSRESPONSE._serialized_start=282
  _GETPOSTSRESPONSE._serialized_end=345
  _GETPOSTCOUNTREQUEST._serialized_start=347
  _GETPOSTCOUNTREQUEST._serialized_end=368
  _GETPOSTCOUNTRESPONSE._serialized_start=370
  _GETPOSTCOUNTRESPONSE._serialized_end=430
  _BLOGSERVICE._serialized_start=433
  _BLOGSERVICE._serialized_end=611
# @@protoc_insertion_point(module_scope)
